name = "kernel"
version = "0.1.0"
defaultTargets = ["kernel"]

[[lean_exe]]
name = "kernel"
root = "Main"

[[require]]
scope = "leanprover"
name = "lean4export"
rev = "3de59f10bc4b4a0f2de698597aeb1246caa0df0a"

[[require]]
scope = "leanprover"
name = "Lean4Checker"
rev = "b7398199245524275543dec6113229c9bb4902e5"
