import Init

/-!
# Lean Kernel Challenge problem `polydisc` — SPEC (trusted, locked)

Every input selects a monic degree-24 integer polynomial. Five coefficient-
scale bands cover the public calibration range; each complete input continues
to seed a large family rather than selecting from a small fixed answer table.
All 24 non-leading coefficients are nonzero and are generated by one linear
pass over the MMIX LCG stream.

The discriminant is computed with a normal subresultant polynomial remainder
sequence.  An abnormal degree drop or failed exact division falls back to the
reduced 24 by 24 monic resultant matrix and fraction-free Bareiss elimination.
Making that construction part of the trusted definition gives the shipped
baseline a reflexive correctness proof, while leaving faster representations
and algorithms open to competitors.
-/


/-! ## Large parametric polynomial bank -/

def lcgA : Nat := 6364136223846793005
def lcgC : Nat := 1442695040888963407
def lcgM : Nat := 18446744073709551616

def lcgNext (state : Nat) : Nat := (lcgA * state + lcgC) % lcgM

def lcgSeed (n : Nat) : Nat := (lcgA * (n + 1) + lcgC) % lcgM

/-- Coefficient-scale bands are deliberately much wider than the judge's relative
jitter.  A geometric schedule from `2^18` through `2^63` with ten points puts
two independently seeded inputs in each band. -/
def difficultyLevel (n : Nat) : Nat :=
  if n < 67108864 then 0                  -- 2^26
  else if n < 68719476736 then 1          -- 2^36
  else if n < 70368744177664 then 2       -- 2^46
  else if n < 72057594037927936 then 3    -- 2^56
  else 4

/-- Maximum coefficient width for the five calibrated scale levels. -/
def kbitsOf (n : Nat) : Nat :=
  match difficultyLevel n with
  | 0 => 15
  | 1 => 36
  | 2 => 205
  | 3 => 1001
  | _ => 3484

def clampWidth (k width : Nat) : Nat := min k (max 2 width)

/-- Width of the `i`th non-leading coefficient, for `1 <= i <= 24`.

The two low-width levels rise quickly and then saturate, mirroring the total
coefficient sizes of the public calibration polynomials.  Larger levels use
one mildly concave ramp.  The profile depends only on the scale and position;
it does not encode any calibration polynomial or discriminant. -/
def coefficientWidth (k i : Nat) : Nat :=
  if k <= 64 then
    let base := 2 * (36 - k) / 7
    let span := 10 + base
    clampWidth k (base + (k - base) * i / span)
  else
    let numerator := (k - 3) * (102 * 24 * i - 2 * i * i)
    let denominator := 100 * 576
    clampWidth k (3 + (numerator + denominator - 1) / denominator)

/-- Assemble consecutive 64-bit LCG outputs little-endian, visiting each state
exactly once and returning the state following the assembled word. -/
def collectCoeffWord : Nat → Nat → Nat → Nat × Nat
  | 0, _, state => (0, state)
  | words + 1, shift, state =>
      let state' := lcgNext state
      let (tail, finalState) := collectCoeffWord words (shift + 64) state'
      (state' * 2 ^ shift + tail, finalState)

/-- Extract the high `k` bits and center them around zero.  A generated zero is
mapped to one, guaranteeing dense inputs without increasing the width bound. -/
def centeredNonzeroCoeff (k words word : Nat) : Int :=
  let coefficient :=
    Int.ofNat (word >>> (64 * words - k)) - Int.ofNat (2 ^ (k - 1))
  if coefficient == 0 then 1 else coefficient

def coefficientsFrom : Nat → Nat → Nat → Nat → List Int
  | 0, _, _, _ => []
  | count + 1, k, index, state =>
      let width := coefficientWidth k index
      let words := (width + 63) / 64
      let (word, state') := collectCoeffWord words 0 state
      centeredNonzeroCoeff width words word ::
        coefficientsFrom count k (index + 1) state'

/-- A monic polynomial with exactly 24 non-leading, nonzero coefficients for
every input `n`.  Coefficients are ordered from highest to lowest degree. -/
def polyOf (n : Nat) : List Int :=
  let k := kbitsOf n
  1 :: coefficientsFrom 24 k 1 (lcgSeed n)

def derivHL (p : List Int) : List Int :=
  let degree := p.length - 1
  (List.range degree).map fun i =>
    Int.ofNat (degree - i) * p.getD i 0

/-! ## Optimized fraction-free determinant -/

def pullPivot :
    List (List Int) → Option (Bool × List Int × List (List Int))
  | [] => none
  | [] :: rows =>
      match pullPivot rows with
      | none => none
      | some (odd, pivot, rest) => some (!odd, pivot, [] :: rest)
  | (first :: tail) :: rows =>
      if first == 0 then
        match pullPivot rows with
        | none => none
        | some (odd, pivot, rest) =>
            some (!odd, pivot, (first :: tail) :: rest)
      else
        some (false, first :: tail, rows)

def pivotOneRow (first : Int) : List Int → List Int → List Int
  | a :: as, b :: bs => (a - first * b) :: pivotOneRow first as bs
  | _, _ => []

def previousOneRow (pivot first : Int) : List Int → List Int → List Int
  | a :: as, b :: bs =>
      (pivot * a - first * b) :: previousOneRow pivot first as bs
  | _, _ => []

def scalePreviousOne (pivot : Int) : List Int → List Int
  | [] => []
  | a :: as => pivot * a :: scalePreviousOne pivot as

def exactRow (previous pivot first : Int) : List Int → List Int → List Int
  | a :: as, b :: bs =>
      (pivot * a - first * b) / previous ::
        exactRow previous pivot first as bs
  | _, _ => []

def exactScale (previous pivot : Int) : List Int → List Int
  | [] => []
  | a :: as => (pivot * a) / previous :: exactScale previous pivot as

def eliminatePivotOne (pivotTail : List Int) :
    List (List Int) → List (List Int)
  | [] => []
  | [] :: rows => [] :: eliminatePivotOne pivotTail rows
  | (first :: tail) :: rows =>
      (if first == 0 then tail else pivotOneRow first tail pivotTail) ::
        eliminatePivotOne pivotTail rows

def eliminatePreviousOne (pivot : Int) (pivotTail : List Int) :
    List (List Int) → List (List Int)
  | [] => []
  | [] :: rows => [] :: eliminatePreviousOne pivot pivotTail rows
  | (first :: tail) :: rows =>
      (if first == 0 then scalePreviousOne pivot tail
       else previousOneRow pivot first tail pivotTail) ::
        eliminatePreviousOne pivot pivotTail rows

def eliminateExact (previous pivot : Int) (pivotTail : List Int) :
    List (List Int) → List (List Int)
  | [] => []
  | [] :: rows => [] :: eliminateExact previous pivot pivotTail rows
  | (first :: tail) :: rows =>
      (if first == 0 then
         if pivot == previous then tail else exactScale previous pivot tail
       else exactRow previous pivot first tail pivotTail) ::
        eliminateExact previous pivot pivotTail rows

def bareissDetGo : Nat → Int → Bool → List (List Int) → Int
  | _, _, negative, [] => if negative then -1 else 1
  | _, _, negative, [[x]] => if negative then -x else x
  | 0, _, _, _ => 0
  | fuel + 1, previous, negative, rows =>
      match pullPivot rows with
      | none => 0
      | some (odd, pivotRow, remaining) =>
          match pivotRow with
          | [] => 0
          | pivot :: pivotTail =>
              let next :=
                if previous == 1 then
                  if pivot == 1 then eliminatePivotOne pivotTail remaining
                  else eliminatePreviousOne pivot pivotTail remaining
                else eliminateExact previous pivot pivotTail remaining
              bareissDetGo fuel pivot
                (if odd then !negative else negative) next

def bareissDet (rows : List (List Int)) : Int :=
  bareissDetGo rows.length 1 false rows

/-! ## Direct monic resultant matrix -/

/-- Coefficients of `x * r - lead(r) * p`, after dropping the cancelled
leading coefficient.  Here `pTail` is a monic polynomial without its leading
one. -/
def shiftedSubtract (lead : Int) : List Int → List Int → List Int
  | a :: as, coefficient :: coefficients =>
      (a - lead * coefficient) :: shiftedSubtract lead as coefficients
  | [], coefficient :: coefficients =>
      (-lead * coefficient) :: shiftedSubtract lead [] coefficients
  | _, [] => []

def monicMulXMod (pTail : List Int) : List Int → List Int
  | [] => []
  | lead :: tail => shiftedSubtract lead tail pTail

def monicRemainderRowsGo :
    Nat → List Int → List Int → List (List Int) → List (List Int)
  | 0, _, _, rows => rows
  | fuel + 1, pTail, row, rows =>
      monicRemainderRowsGo fuel pTail (monicMulXMod pTail row) (row :: rows)

/-- The degree-by-degree matrix with rows
`x^(d-1) p' mod p, ..., x p' mod p, p'`. -/
def monicReducedSylvester (p q : List Int) : List (List Int) :=
  match p with
  | 1 :: pTail => monicRemainderRowsGo (p.length - 1) pTail q []
  | _ => []

/-! ## Normal subresultant PRS with a Bareiss fallback -/

def trimLeading : List Int → List Int
  | [] => []
  | 0 :: coefficients => trimLeading coefficients
  | coefficient :: coefficients => coefficient :: coefficients

def scalePolynomial (factor : Int) : List Int → List Int
  | [] => []
  | coefficient :: coefficients =>
      factor * coefficient :: scalePolynomial factor coefficients

/-- After the leading terms cancel, combine the remaining coefficients of
`lcG * r - lcR * x^j * g`.  Both inputs are high-to-low tails. -/
def cancelPseudoLeading (lcG lcR : Int) : List Int → List Int → List Int
  | coefficient :: coefficients, divisor :: divisors =>
      (lcG * coefficient - lcR * divisor) ::
        cancelPseudoLeading lcG lcR coefficients divisors
  | coefficient :: coefficients, [] =>
      lcG * coefficient :: cancelPseudoLeading lcG lcR coefficients []
  | [], _ => []

def pseudoRemainderGo :
    Nat → Nat → List Int → List Int → Option (List Int)
  | 0, _, _, _ => none
  | fuel + 1, remaining, divisor, dividend =>
      let dividend := trimLeading dividend
      if dividend.length < divisor.length then
        some (scalePolynomial ((divisor.headD 0) ^ remaining) dividend)
      else
        match divisor, dividend with
        | lcG :: divisorTail, lcR :: dividendTail =>
            let next :=
              trimLeading
                (cancelPseudoLeading lcG lcR dividendTail divisorTail)
            pseudoRemainderGo fuel (remaining - 1) divisor next
        | _, _ => none

def pseudoRemainder (dividend divisor : List Int) : Option (List Int) :=
  let dividend := trimLeading dividend
  let divisor := trimLeading divisor
  if divisor.isEmpty then none
  else if dividend.length < divisor.length then some dividend
  else
    pseudoRemainderGo (dividend.length + 1)
      (dividend.length - divisor.length + 1) divisor dividend

def exactDividePolynomial (divisor : Int) : List Int → Option (List Int)
  | [] => some []
  | coefficient :: coefficients =>
      if divisor == 0 || coefficient % divisor != 0 then none
      else
        match exactDividePolynomial divisor coefficients with
        | none => none
        | some quotient => some (coefficient / divisor :: quotient)

/-- Brown's subresultant PRS specialized to the normal case.  For consecutive
degrees the post-initial scaling factor is the square of the previous leading
coefficient.  Any abnormal step returns `none` and uses the Bareiss fallback. -/
def normalResultantGo :
    Nat → Bool → List Int → List Int → Option Int
  | 0, _, _, _ => none
  | fuel + 1, initial, f, g =>
      match pseudoRemainder f g with
      | none => none
      | some raw =>
          let divided :=
            if initial then some raw
            else exactDividePolynomial ((f.headD 0) ^ 2) raw
          match divided with
          | none => none
          | some coefficients =>
              match trimLeading coefficients with
              | [] => some 0
              | remainder =>
                  if remainder.length + 1 == g.length then
                    match remainder with
                    | [constant] => some constant
                    | _ => normalResultantGo fuel false g remainder
                  else
                    none

def normalResultant (f g : List Int) : Option Int :=
  let f := trimLeading f
  let g := trimLeading g
  if f.length == g.length + 1 && !g.isEmpty then
    normalResultantGo (g.length + 1) true f g
  else
    none

def resultantFromPoly (p : List Int) : Int :=
  let derivative := derivHL p
  match normalResultant p derivative with
  | some resultant => resultant
  | none => bareissDet (monicReducedSylvester p derivative)

def discriminantFromPoly (p : List Int) : Int :=
  let degree := p.length - 1
  let sign : Int :=
    if degree * (degree - 1) / 2 % 2 = 0 then 1 else -1
  sign * resultantFromPoly p

/-- Parametric degree-24 discriminant specification. -/
def discSpec (n : Nat) : Int := discriminantFromPoly (polyOf n)
