#!/usr/bin/env python3
"""Synchronize public participant packages from authoritative evaluator workspaces.

Only fixed specification and environment files are generated.  A participant's
``Submission.lean`` is user-owned and is never read, replaced, or deleted.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys

from problem_layout import MIGRATED_PROBLEMS, evaluation_problem_dir


ROOT = Path(__file__).resolve().parents[1]
MATHLIB_PARTICIPANT_PROBLEMS = ("fib", "mertens", "primecount")
CORE_PARTICIPANT_PROBLEMS = tuple(sorted(MIGRATED_PROBLEMS - set(MATHLIB_PARTICIPANT_PROBLEMS)))
SETUP_TEMPLATE = Path(__file__).resolve().parent / "templates/participant_setup.py.in"


def _package_name(canonical: Path) -> str:
    source = (canonical / "lakefile.toml").read_text()
    match = re.search(r'^name\s*=\s*"([A-Za-z0-9_-]+)"\s*$', source, re.MULTILINE)
    if match is None:
        raise ValueError(f"canonical evaluator lakefile has no simple package name: {canonical}")
    return match.group(1)


def mathlib_cache_modules(specification: str) -> list[str]:
    """Return the fixed Spec's direct Mathlib imports as cache file paths."""
    modules = []
    for line in specification.splitlines():
        match = re.match(r"^\s*(?:public\s+)?import\s+(.+)$", line.split("--", 1)[0])
        if match is None:
            continue
        for module in match.group(1).split():
            if module.startswith("Mathlib."):
                if not re.fullmatch(r"Mathlib(?:\.[A-Za-z0-9_]+)+", module):
                    raise ValueError(f"unsupported Mathlib import: {module}")
                path = module.replace(".", "/") + ".lean"
                if path not in modules:
                    modules.append(path)
    if not modules:
        raise ValueError("Mathlib participant Spec must declare direct Mathlib imports")
    return modules


def _mathlib_environment(canonical: Path, package: str) -> tuple[dict, str]:
    manifest = json.loads((canonical / "lake-manifest.json").read_text())
    if manifest.get("packagesDir") != ".lake/packages":
        raise ValueError("Mathlib evaluator manifest must use .lake/packages")
    packages = manifest.get("packages", [])
    if any(not re.fullmatch(r"[A-Za-z0-9_-]+", entry["name"])
           or not re.fullmatch(r"[0-9a-f]{40}", entry["rev"]) for entry in packages):
        raise ValueError("Mathlib evaluator manifest must contain exact package revisions")
    mathlib = [entry for entry in packages if entry["name"] == "mathlib"]
    if len(mathlib) != 1:
        raise ValueError("Mathlib evaluator manifest must contain exactly one mathlib package")
    manifest["name"] = package
    requirement = (
        '[[require]]\nname = "mathlib"\n'
        f'git = {json.dumps(mathlib[0]["url"])}\n'
        f'rev = {json.dumps(mathlib[0]["rev"])}\n\n'
    )
    return manifest, requirement


def expected_files(problem: str, root: Path = ROOT) -> dict[str, str]:
    """Return fixed public files, preserving the evaluator's exact dependency pins."""
    if problem not in MIGRATED_PROBLEMS:
        raise ValueError(f"not a participant problem: {problem}")
    canonical = evaluation_problem_dir(root, problem)
    if not (canonical / "config.json").is_file():
        raise ValueError(f"missing evaluator workspace: {canonical}")
    canonical_lakefile = (canonical / "lakefile.toml").read_text()
    is_mathlib = problem in MATHLIB_PARTICIPANT_PROBLEMS
    if not is_mathlib and "[[require]]" in canonical_lakefile:
        raise ValueError(
            f"core participant problem unexpectedly declares dependencies: {canonical}"
        )
    package = "fib" if problem == "fib" else _package_name(canonical)
    canonical_manifest = canonical / "lake-manifest.json"
    if not is_mathlib and canonical_manifest.exists():
        manifest_value = json.loads(canonical_manifest.read_text())
        if (manifest_value.get("packagesDir") != ".lake/packages"
                or manifest_value.get("packages") != []
                or manifest_value.get("name") != package):
            raise ValueError(
                f"core evaluator manifest is not an empty matching environment: {canonical_manifest}"
            )
    manifest = {
        "version": "1.2.0",
        "packagesDir": ".lake/packages",
        "packages": [],
        "name": package,
        "lakeDir": ".lake",
        "fixedToolchain": False,
    }
    requirement = ""
    if is_mathlib:
        manifest, requirement = _mathlib_environment(canonical, package)
    lakefile = (
        '# Generated by scripts/sync_participants.py; edit only Submission.lean.\n'
        f'name = {json.dumps(package)}\n'
        'defaultTargets = ["Submission"]\n\n'
        '[leanOptions]\n'
        'autoImplicit = false\n'
        'warningAsError = true\n\n'
        + requirement +
        '[[lean_lib]]\n'
        'name = "Spec"\n\n'
        '[[lean_lib]]\n'
        'name = "Submission"\n'
    )
    specification = (canonical / "Spec.lean").read_text()
    files = {
        "Spec.lean": specification,
        "lakefile.toml": lakefile,
        "lake-manifest.json": json.dumps(manifest, indent=2) + "\n",
        "lean-toolchain": (canonical / "lean-toolchain").read_text(),
    }
    if is_mathlib:
        modules = mathlib_cache_modules(specification)
        files["setup.py"] = SETUP_TEMPLATE.read_text().replace(
            "__LKC_MATHLIB_MODULES__", json.dumps(modules)
        )
    return files


def _matches(name: str, actual: str | None, expected: str) -> bool:
    if actual is None:
        return False
    if name.endswith(".json"):
        try:
            return json.loads(actual) == json.loads(expected)
        except json.JSONDecodeError:
            return False
    return actual == expected


def synchronize_problem(problem: str, root: Path = ROOT, *, check: bool = False) -> list[str]:
    """Synchronize one problem, preserving ``Submission.lean`` unconditionally."""
    participant = root / "problems" / problem
    if not participant.is_dir():
        raise ValueError(f"missing participant directory: {participant}")
    mismatched = []
    for name, expected in expected_files(problem, root).items():
        path = participant / name
        actual = path.read_text() if path.is_file() and not path.is_symlink() else None
        if not _matches(name, actual, expected):
            mismatched.append(name)
            if not check:
                path.write_text(expected)
    if mismatched and check:
        raise ValueError(f"participant {problem} is out of sync: " + ", ".join(mismatched))
    return mismatched


def synchronize(root: Path = ROOT, *, problems=None, check: bool = False) -> dict[str, list[str]]:
    """Synchronize selected migrated problems, or all of them by default."""
    selected = tuple(sorted(MIGRATED_PROBLEMS if problems is None else set(problems)))
    unknown = set(selected) - MIGRATED_PROBLEMS
    if unknown:
        raise ValueError("unknown migrated problem(s): " + ", ".join(sorted(unknown)))
    changed = {}
    errors = []
    for problem in selected:
        try:
            changed[problem] = synchronize_problem(problem, root, check=check)
        except ValueError as exc:
            errors.append(str(exc))
    if errors:
        raise ValueError("; ".join(errors))
    return changed


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--problem", action="append", choices=sorted(MIGRATED_PROBLEMS))
    parser.add_argument("--check", action="store_true", help="check without writing anything")
    args = parser.parse_args(argv)
    try:
        changed = synchronize(problems=args.problem, check=args.check)
        if args.check:
            print("Participant specifications and environments match the evaluator.")
        else:
            rendered = [f"{problem}: {', '.join(files) or 'already current'}"
                        for problem, files in changed.items()]
            print("Synchronized participant packages. " + "; ".join(rendered))
        return 0
    except (OSError, ValueError, KeyError) as exc:
        print(exc, file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
