#!/usr/bin/env python3
"""Generate only participant environment files from the authoritative fib pins."""

import argparse
import json
from pathlib import Path
import sys

from problem_layout import evaluation_problem_dir


ROOT = Path(__file__).resolve().parents[1]


def expected_files(root=ROOT):
    canonical = evaluation_problem_dir(root, "fib")
    manifest = json.loads((canonical / "lake-manifest.json").read_text())
    mathlib = next(package for package in manifest["packages"] if package["name"] == "mathlib")
    manifest["name"] = "fib"
    lakefile = (
        '# Generated by scripts/sync_fib_participant.py; do not change dependency pins.\n'
        'name = "fib"\ndefaultTargets = ["Submission"]\n\n'
        '[leanOptions]\nautoImplicit = false\nwarningAsError = true\n\n'
        f'[[require]]\nname = "mathlib"\ngit = {json.dumps(mathlib["url"])}\n'
        f'rev = {json.dumps(mathlib["rev"])}\n\n'
        '[[lean_lib]]\nname = "Submission"\n'
    )
    return {
        "lakefile.toml": lakefile,
        "lake-manifest.json": json.dumps(manifest, indent=2) + "\n",
        "lean-toolchain": (canonical / "lean-toolchain").read_text(),
    }


def synchronize(root=ROOT, *, check=False):
    participant = root / "problems/fib"
    mismatched = []
    for name, expected in expected_files(root).items():
        path = participant / name
        actual = path.read_text() if path.is_file() else None
        # Lake may reformat its manifest without changing the pinned content.
        matches = (json.loads(actual) == json.loads(expected)
                   if name.endswith(".json") and actual is not None else actual == expected)
        if not matches:
            mismatched.append(name)
            if not check:
                path.write_text(expected)
    if mismatched and check:
        raise ValueError("participant environment is out of sync: " + ", ".join(mismatched))
    return mismatched


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check without writing anything")
    args = parser.parse_args()
    try:
        changed = synchronize(check=args.check)
        print("Participant environment pins match the evaluator." if args.check
              else "Generated participant environment: " + (", ".join(changed) or "already current"))
        return 0
    except (OSError, ValueError, KeyError, StopIteration) as error:
        print(error, file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
