#!/usr/bin/env python3
"""Synchronize public participant packages from authoritative evaluator workspaces.

Only fixed specification and environment files are generated.  A participant's
``Submission.lean`` is user-owned and is never read, replaced, or deleted.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys

from problem_layout import MIGRATED_PROBLEMS, evaluation_problem_dir
import sync_fib_participant


ROOT = Path(__file__).resolve().parents[1]
CORE_PARTICIPANT_PROBLEMS = tuple(sorted(MIGRATED_PROBLEMS - {"fib"}))


def _package_name(canonical: Path) -> str:
    source = (canonical / "lakefile.toml").read_text()
    match = re.search(r'^name\s*=\s*"([A-Za-z0-9_-]+)"\s*$', source, re.MULTILINE)
    if match is None:
        raise ValueError(f"canonical evaluator lakefile has no simple package name: {canonical}")
    return match.group(1)


def expected_files(problem: str, root: Path = ROOT) -> dict[str, str]:
    """Return generated public files for one migrated core-only problem."""
    if problem not in CORE_PARTICIPANT_PROBLEMS:
        raise ValueError(f"not a core participant problem: {problem}")
    canonical = evaluation_problem_dir(root, problem)
    if not (canonical / "config.json").is_file():
        raise ValueError(f"missing evaluator workspace: {canonical}")
    canonical_lakefile = (canonical / "lakefile.toml").read_text()
    if "[[require]]" in canonical_lakefile:
        raise ValueError(
            f"core participant problem unexpectedly declares dependencies: {canonical}"
        )
    package = _package_name(canonical)
    canonical_manifest = canonical / "lake-manifest.json"
    if canonical_manifest.exists():
        manifest_value = json.loads(canonical_manifest.read_text())
        if (manifest_value.get("packagesDir") != ".lake/packages"
                or manifest_value.get("packages") != []
                or manifest_value.get("name") != package):
            raise ValueError(
                f"core evaluator manifest is not an empty matching environment: {canonical_manifest}"
            )
    lakefile = (
        '# Generated by scripts/sync_participants.py; edit only Submission.lean.\n'
        f'name = {json.dumps(package)}\n'
        'defaultTargets = ["Submission"]\n\n'
        '[leanOptions]\n'
        'autoImplicit = false\n'
        'warningAsError = true\n\n'
        '[[lean_lib]]\n'
        'name = "Spec"\n\n'
        '[[lean_lib]]\n'
        'name = "Submission"\n'
    )
    manifest = {
        "version": "1.2.0",
        "packagesDir": ".lake/packages",
        "packages": [],
        "name": package,
        "lakeDir": ".lake",
        "fixedToolchain": False,
    }
    return {
        "Spec.lean": (canonical / "Spec.lean").read_text(),
        "lakefile.toml": lakefile,
        "lake-manifest.json": json.dumps(manifest, indent=2) + "\n",
        "lean-toolchain": (canonical / "lean-toolchain").read_text(),
    }


def _matches(name: str, actual: str | None, expected: str) -> bool:
    if actual is None:
        return False
    if name.endswith(".json"):
        try:
            return json.loads(actual) == json.loads(expected)
        except json.JSONDecodeError:
            return False
    return actual == expected


def synchronize_problem(problem: str, root: Path = ROOT, *, check: bool = False) -> list[str]:
    """Synchronize one problem, preserving ``Submission.lean`` unconditionally."""
    if problem == "fib":
        return sync_fib_participant.synchronize(root, check=check)
    participant = root / "problems" / problem
    if not participant.is_dir():
        raise ValueError(f"missing participant directory: {participant}")
    mismatched = []
    for name, expected in expected_files(problem, root).items():
        path = participant / name
        actual = path.read_text() if path.is_file() and not path.is_symlink() else None
        if not _matches(name, actual, expected):
            mismatched.append(name)
            if not check:
                path.write_text(expected)
    if mismatched and check:
        raise ValueError(f"participant {problem} is out of sync: " + ", ".join(mismatched))
    return mismatched


def synchronize(root: Path = ROOT, *, problems=None, check: bool = False) -> dict[str, list[str]]:
    """Synchronize selected migrated problems, or all of them by default."""
    selected = tuple(sorted(MIGRATED_PROBLEMS if problems is None else set(problems)))
    unknown = set(selected) - MIGRATED_PROBLEMS
    if unknown:
        raise ValueError("unknown migrated problem(s): " + ", ".join(sorted(unknown)))
    changed = {}
    errors = []
    for problem in selected:
        try:
            changed[problem] = synchronize_problem(problem, root, check=check)
        except ValueError as exc:
            errors.append(str(exc))
    if errors:
        raise ValueError("; ".join(errors))
    return changed


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--problem", action="append", choices=sorted(MIGRATED_PROBLEMS))
    parser.add_argument("--check", action="store_true", help="check without writing anything")
    args = parser.parse_args(argv)
    try:
        changed = synchronize(problems=args.problem, check=args.check)
        if args.check:
            print("Participant specifications and environments match the evaluator.")
        else:
            rendered = [f"{problem}: {', '.join(files) or 'already current'}"
                        for problem, files in changed.items()]
            print("Synchronized participant packages. " + "; ".join(rendered))
        return 0
    except (OSError, ValueError, KeyError) as exc:
        print(exc, file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
