name = "track2mertens"
defaultTargets = ["Challenge", "Solution"]

[leanOptions]
autoImplicit = false

[[lean_lib]]
name = "Spec"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"

[[lean_lib]]
name = "Submission"
